# ✅ Formato correcto
spring.datasource.url=jdbc:postgresql://dpg-d7i77e2qqhas738t88h0-a.oregon-postgres.render.com:5432/tutorcompanion
spring.datasource.username=tutorcompanion_user
spring.datasource.password=Iv5knVODyPsf6ay0HE9E1VERmPj67B3a
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.session.jdbc.initialize-schema=always