# ✅ Formato correcto
spring.datasource.url=jdbc:postgresql://dpg-d866dih9rddc73f1p18g-a.oregon-postgres.render.com:5432/tutorcompanion_eu02
spring.datasource.username=tutorcompanion_eu02_user
spring.datasource.password=e3Ty6367EYin8kZgTM33BgJYlSURN4jJ
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.session.jdbc.initialize-schema=always